$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$Src=Join-Path $Root 'src\Program.cs';$Runtime=Join-Path $Root 'runtime';$Build=Join-Path $Root 'build';$Logo=Join-Path $Build 'kyp-logo.png'
$CSC="$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
New-Item -ItemType Directory -Force -Path $Build|Out-Null
Invoke-WebRequest 'https://kyp.mciedu.com/downloads/kyp-iris/kyp-logo.png' -OutFile $Logo
if(!(Test-Path $Logo)){throw 'Official KYP logo download failed.'}
$Text=Get-Content $Src -Raw
$Text=$Text.Replace('IrisData d=null;','IrisData d=new IrisData();').Replace('if(d!=null&&d.BitmapImage!=null)','if(d.BitmapImage!=null)').Replace('IrisData probe=null;','IrisData probe=new IrisData();').Replace('if(probe!=null&&probe.BitmapImage!=null)','if(probe.BitmapImage!=null)')
$Text=$Text.Replace('IrisData Capture(out int quality)','IrisData CaptureIris(out int quality)').Replace('d=Capture(out q);','d=CaptureIris(out q);').Replace('probe=Capture(out q);','probe=CaptureIris(out q);')
$Text=$Text.Replace('TextBox token; ComboBox students,eye,courses,sessions;','TextBox token; ComboBox students,eye,courses,sessions; Label programme;')
$Text=$Text.Replace('UI();LoadToken();','UI();Premium();LoadToken();')
$marker=' protected override void OnFormClosed(FormClosedEventArgs e)'
$premium=@'
 Control FindText(Control root,string text){foreach(Control c in root.Controls){if(c.Text==text)return c;Control z=FindText(c,text);if(z!=null)return z;}return null;}
 Label AddLabel(Control parent,string text,int x,int y,int w,int h,float size,bool bold,Color color){Label l=new Label();l.Text=text;l.SetBounds(x,y,w,h);l.Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular);l.ForeColor=color;l.BackColor=Color.Transparent;parent.Controls.Add(l);return l;}
 void Premium(){
  Text="KYP Iris Connector V3.2 - Kushal Youth Programme";Width=1280;Height=850;MinimumSize=new Size(1200,800);BackColor=Color.FromArgb(244,249,255);
  Panel header=null;foreach(Control c in Controls){Panel p=c as Panel;if(p!=null&&p.Top==0){header=p;break;}}
  if(header!=null){header.SetBounds(0,0,1280,150);header.BackColor=Color.FromArgb(5,55,118);foreach(Control c in header.Controls)c.Visible=false;string lp=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"kyp-logo.png");if(File.Exists(lp)){PictureBox pic=new PictureBox();pic.Image=Image.FromFile(lp);pic.SizeMode=PictureBoxSizeMode.Zoom;pic.BackColor=Color.White;pic.SetBounds(24,14,120,120);header.Controls.Add(pic);}AddLabel(header,"Kushal Youth Programme",170,20,680,48,28,true,Color.White);AddLabel(header,"Skills for the Digital Future",172,70,430,28,13,false,Color.FromArgb(220,238,255));AddLabel(header,"Secure Biometric Attendance Connector  |  Mantra MIS100V2",172,105,650,25,11,false,Color.White);Label v=AddLabel(header,"V3.2\nSECURE EDITION",1050,35,170,70,11,true,Color.White);v.TextAlign=ContentAlignment.MiddleCenter;v.BorderStyle=BorderStyle.FixedSingle;}
  Control sec=FindText(this,"Secure Connector");if(sec!=null)sec.Visible=false;token.Visible=false;
  Control save=FindText(this,"Save Securely");if(save!=null){save.SetBounds(1080,165,150,40);StyleButton(save,Color.FromArgb(5,80,165),Color.White);}Control test=FindText(this,"Test Server");if(test!=null){test.SetBounds(915,165,150,40);StyleButton(test,Color.White,Color.FromArgb(5,65,135));}
  server.SetBounds(35,168,245,55);device.SetBounds(305,168,270,55);server.Font=new Font("Segoe UI",11,FontStyle.Bold);device.Font=new Font("Segoe UI",11,FontStyle.Bold);AddStatusCard("STUDENTS","Not loaded",595,160,145,62);AddStatusCard("KYP COURSE MODULES","Not loaded",755,160,145,62);
  Control detect=FindText(this,"Detect MIS100V2");if(detect!=null){detect.SetBounds(305,225,260,38);StyleButton(detect,Color.White,Color.FromArgb(5,65,135));}Control ls=FindText(this,"Load Students");if(ls!=null){ls.SetBounds(595,225,145,38);StyleButton(ls,Color.White,Color.FromArgb(5,65,135));}Control lc=FindText(this,"Load Courses / Sessions");if(lc!=null){lc.Text="Load KYP Modules / Sessions";lc.SetBounds(755,225,210,38);StyleButton(lc,Color.White,Color.FromArgb(5,65,135));}
  Panel enroll=null,att=null;foreach(Control c in Controls){Panel p=c as Panel;if(p!=null&&p.Top>200){if(enroll==null)enroll=p;else if(att==null)att=p;}}
  if(enroll!=null){enroll.SetBounds(30,290,575,405);enroll.BackColor=Color.White;StylePanel(enroll);AddLabel(enroll,"Student",25,50,120,22,9,true,Color.FromArgb(30,50,75));AddLabel(enroll,"Eye",25,115,120,22,9,true,Color.FromArgb(30,50,75));students.SetBounds(25,75,520,32);eye.SetBounds(25,140,220,32);Control eb=FindText(enroll,"Capture & Enroll Iris");if(eb!=null){eb.SetBounds(25,205,520,54);StyleButton(eb,Color.FromArgb(0,151,92),Color.White);}foreach(Control c in enroll.Controls){Label l=c as Label;if(l!=null&&l.Text.StartsWith("Biometric material"))l.SetBounds(25,285,520,60);}}
  if(att!=null){att.SetBounds(630,290,600,405);att.BackColor=Color.White;StylePanel(att);Control sb=FindText(att,"Scan & Identify Student");if(sb!=null){sb.SetBounds(25,55,550,50);StyleButton(sb,Color.White,Color.FromArgb(5,65,135));}matched.SetBounds(25,112,550,34);AddLabel(att,"Programme",25,150,100,20,9,true,Color.FromArgb(30,50,75));programme=AddLabel(att,"Kushal Youth Programme (KYP)",25,172,550,30,10,true,Color.FromArgb(5,65,135));AddLabel(att,"KYP Course Module",25,210,170,20,9,true,Color.FromArgb(30,50,75));AddLabel(att,"Today's Session",305,210,170,20,9,true,Color.FromArgb(30,50,75));courses.SetBounds(25,232,265,32);sessions.SetBounds(305,232,270,32);Control ci=FindText(att,"CHECK-IN");if(ci!=null){ci.SetBounds(25,282,265,52);StyleButton(ci,Color.FromArgb(0,151,92),Color.White);}Control co=FindText(att,"CHECK-OUT");if(co!=null){co.SetBounds(305,282,270,52);StyleButton(co,Color.FromArgb(215,42,46),Color.White);}foreach(Control c in att.Controls){Label l=c as Label;if(l!=null&&l.Text.StartsWith("A fresh iris match")){l.SetBounds(25,345,550,45);l.Text="Fresh iris match required for every Check-In / Check-Out. 110 verified minutes required.";l.ForeColor=Color.FromArgb(45,70,100);}}}
  status.SetBounds(30,705,1200,42);status.Font=new Font("Segoe UI",10);status.ForeColor=Color.FromArgb(45,70,100);Label footer=new Label();footer.Text="Downloads & Resources     |     KYP Portal     |     User Manual     |     Support                         Kushal Youth Programme  •  V3.2";footer.TextAlign=ContentAlignment.MiddleCenter;footer.Font=new Font("Segoe UI",10,FontStyle.Bold);footer.ForeColor=Color.FromArgb(5,65,135);footer.BackColor=Color.White;footer.SetBounds(0,760,1280,42);Controls.Add(footer);footer.BringToFront();
 }
 void AddStatusCard(string title,string value,int x,int y,int w,int h){Panel p=new Panel();p.SetBounds(x,y,w,h);p.BackColor=Color.White;p.BorderStyle=BorderStyle.FixedSingle;Controls.Add(p);AddLabel(p,title,10,8,w-20,20,8,true,Color.FromArgb(5,65,135));AddLabel(p,value,10,31,w-20,20,9,true,Color.DimGray);p.BringToFront();}
 void StylePanel(Panel p){p.BorderStyle=BorderStyle.FixedSingle;}
 void StyleButton(Control c,Color bg,Color fg){Button b=c as Button;if(b==null)return;b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderColor=Color.FromArgb(170,195,225);b.FlatAppearance.BorderSize=1;b.BackColor=bg;b.ForeColor=fg;b.Font=new Font("Segoe UI",10,FontStyle.Bold);b.Cursor=Cursors.Hand;}
'@
if($Text -notmatch 'void Premium\('){$Text=$Text.Replace($marker,"`r`n"+$premium+$marker)}
$Patched=Join-Path $Build 'Program.cs';Set-Content $Patched $Text -Encoding UTF8
$Required=@('MIDIris_Auth.dll','MIDIris_Auth_Core.dll','MR014_MIS100V2_Windows_Auth_IPL.dll','iris_engine_v3.dll','iris_image_record.dll');foreach($Name in $Required){if(!(Test-Path (Join-Path $Runtime $Name))){throw "Missing Mantra runtime: $Name"}}
$Exe=Join-Path $Build 'KYP-Iris-Connector-V3.2.exe';& $CSC /nologo /target:winexe /platform:x64 /out:$Exe /reference:System.dll /reference:System.Drawing.dll /reference:System.Windows.Forms.dll /reference:System.Web.Extensions.dll /reference:System.Security.dll /reference:"$Runtime\MIDIris_Auth.dll" $Patched
if($LASTEXITCODE -ne 0){throw 'V3.2 compilation failed.'};Copy-Item "$Runtime\*.dll" $Build -Force;Write-Host 'KYP_IRIS_CONNECTOR_V32_LABELS_FINAL=PASS';Write-Host "EXE=$Exe";Start-Process -FilePath $Exe -WorkingDirectory $Build
