@extends('admin.layouts.app')
@section('title','Auto Reply Center')
@section('content')
<div class="mb-4"><h2 class="fw-bold mb-1">Auto Reply Center</h2><p class="text-muted mb-0">Manage business-wise automatic reply settings, templates and rules.</p></div>
<div class="card p-4 mb-4"><h5 class="fw-bold">Business Auto Reply Controls</h5><div class="row g-3 mt-1">@foreach($institutions as $institution)<div class="col-md-6 col-xl-4"><div class="border rounded p-3 d-flex justify-content-between align-items-center"><div><strong>{{ $institution->name }}</strong><br><small class="text-muted">{{ $institution->sender_email ?: 'Sender email not configured' }}</small></div><form method="POST" action="{{ route('admin.auto-replies.business.toggle',$institution) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $institution->auto_reply_enabled?'btn-success':'btn-outline-secondary' }}">{{ $institution->auto_reply_enabled?'ON':'OFF' }}</button></form></div></div>@endforeach</div></div>
<div class="row g-4">
<div class="col-xl-6"><div class="card p-4 h-100"><h5 class="fw-bold">Create Reply Template</h5><form method="POST" action="{{ route('admin.auto-replies.templates.store') }}">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Business</label><select name="institution_id" class="form-select"><option value="">Global</option>@foreach($institutions as $institution)<option value="{{ $institution->id }}">{{ $institution->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Category</label><input name="category" class="form-control" placeholder="course_fee" required></div><div class="col-md-6"><label class="form-label">Language</label><select name="language" class="form-select"><option value="en">English</option><option value="hi">Hindi</option><option value="roman_hi">Roman Hindi</option><option value="bilingual">Bilingual</option></select></div><div class="col-12"><label class="form-label">Subject</label><input name="subject" class="form-control"></div><div class="col-12"><label class="form-label">Body</label><textarea name="body" rows="6" class="form-control" placeholder="Use placeholders like {customer_name}, {business_name}, {course_name}, {fee}" required></textarea></div><div class="col-md-6"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draft</option><option value="test">Test</option><option value="approved">Approved</option><option value="live">Live</option></select></div><div class="col-md-6 d-flex align-items-end"><button class="btn btn-primary w-100">Save Template</button></div></div></form></div></div>
<div class="col-xl-6"><div class="card p-4 h-100"><h5 class="fw-bold">Create Auto Reply Rule</h5><form method="POST" action="{{ route('admin.auto-replies.rules.store') }}">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Business</label><select name="institution_id" class="form-select"><option value="">Global</option>@foreach($institutions as $institution)<option value="{{ $institution->id }}">{{ $institution->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Template</label><select name="reply_template_id" class="form-select" required>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }} ({{ $template->category }})</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Rule Name</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Category</label><input name="category" class="form-control" required></div><div class="col-12"><label class="form-label">Keywords</label><textarea name="keywords_text" class="form-control" rows="4" placeholder="fee, fees, cost, charge, फीस, kitna lagega"></textarea></div><div class="col-md-4"><label class="form-label">Priority</label><input type="number" name="priority" value="100" class="form-control" required></div><div class="col-md-4"><label class="form-label">Fallback</label><select name="fallback_action" class="form-select"><option value="manual_review">Manual Review</option><option value="acknowledge_only">Acknowledge Only</option><option value="do_nothing">Do Nothing</option></select></div><div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="auto_send" value="1" id="autoSend"><label class="form-check-label" for="autoSend">Auto Send</label></div></div><div class="col-12"><button class="btn btn-primary w-100">Save Rule</button></div></div></form></div></div>
</div>
<div class="card p-4 mt-4"><h5 class="fw-bold">Existing Rules</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Rule</th><th>Business</th><th>Category</th><th>Template</th><th>Priority</th><th>Auto Send</th><th>Status</th></tr></thead><tbody>@forelse($rules as $rule)<tr><td>{{ $rule->name }}</td><td>{{ $rule->institution?->name ?? 'Global' }}</td><td>{{ $rule->category }}</td><td>{{ $rule->template?->name ?? '-' }}</td><td>{{ $rule->priority }}</td><td>{{ $rule->auto_send?'Yes':'No' }}</td><td><form method="POST" action="{{ route('admin.auto-replies.rules.toggle',$rule) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $rule->is_active?'btn-success':'btn-outline-secondary' }}">{{ $rule->is_active?'Active':'Inactive' }}</button></form></td></tr>@empty<tr><td colspan="7" class="text-muted text-center py-4">No auto-reply rules yet.</td></tr>@endforelse</tbody></table></div></div>
@endsection
