@extends('admin.layouts.app')
@section('title','Institutions')
@section('content')
<h2 class="fw-bold mb-4">Institutions</h2>
<div class="card p-4 mb-4"><form method="POST" action="{{ route('admin.institutions.store') }}">@csrf
<div class="row g-3"><div class="col-md-5"><input class="form-control" name="name" placeholder="Institution name" required></div><div class="col-md-5"><input class="form-control" name="website_url" placeholder="https://example.com"></div><div class="col-md-2"><input type="number" class="form-control" name="display_order" value="0" min="0"></div><div class="col-12"><input class="form-control" name="short_description" placeholder="Short description"></div><div class="col-12"><textarea class="form-control" name="description" rows="3" placeholder="Full description"></textarea></div><div class="col-md-5"><input class="form-control" name="logo" placeholder="Logo URL/path"></div><div class="col-md-5"><input class="form-control" name="image" placeholder="Image URL/path"></div><div class="col-md-2"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked> Active</label></div><div class="col-12"><button class="btn btn-primary">Add Institution</button></div></div>
</form></div>
@foreach($items as $item)<div class="card p-3 mb-3"><form method="POST" action="{{ route('admin.institutions.update',$item) }}">@csrf @method('PUT')
<div class="row g-2"><div class="col-md-4"><input class="form-control" name="name" value="{{ $item->name }}" required></div><div class="col-md-4"><input class="form-control" name="website_url" value="{{ $item->website_url }}"></div><div class="col-md-2"><input type="number" class="form-control" name="display_order" value="{{ $item->display_order }}" min="0"></div><div class="col-md-2"><label><input type="checkbox" name="is_active" value="1" @checked($item->is_active)> Active</label></div><div class="col-12"><input class="form-control" name="short_description" value="{{ $item->short_description }}"></div><div class="col-12"><textarea class="form-control" name="description" rows="2">{{ $item->description }}</textarea></div><div class="col-md-5"><input class="form-control" name="logo" value="{{ $item->logo }}" placeholder="Logo URL/path"></div><div class="col-md-5"><input class="form-control" name="image" value="{{ $item->image }}" placeholder="Image URL/path"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Update</button></div></div></form><form method="POST" action="{{ route('admin.institutions.destroy',$item) }}" class="mt-2">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete this institution?')">Delete</button></form></div>@endforeach
@endsection
