@extends('admin.layouts.app')
@section('title','Enquiry #'.$enquiry->id)
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Enquiry #{{ $enquiry->id }}</h2><p class="text-muted mb-0">{{ $enquiry->institution?->name ?? 'MCI Educational Group' }} · {{ $enquiry->name }}</p></div><a href="{{ route('admin.enquiries.index') }}" class="btn btn-outline-secondary">Back</a></div>
<div class="row g-4">
<div class="col-xl-8">
<div class="card p-4 mb-4"><h5 class="fw-bold">Customer Query</h5><div class="row g-3 mt-1"><div class="col-md-4"><small class="text-muted">Name</small><div>{{ $enquiry->name }}</div></div><div class="col-md-4"><small class="text-muted">Phone</small><div>{{ $enquiry->phone ?: '-' }}</div></div><div class="col-md-4"><small class="text-muted">Email</small><div>{{ $enquiry->email ?: '-' }}</div></div><div class="col-12"><small class="text-muted">Subject</small><div>{{ $enquiry->subject ?: '-' }}</div></div><div class="col-12"><small class="text-muted">Message</small><div class="p-3 bg-light rounded">{{ $enquiry->message }}</div></div></div></div>
<div class="card p-4 mb-4"><h5 class="fw-bold">Send Manual Reply</h5><form method="POST" action="{{ route('admin.enquiries.reply',$enquiry) }}">@csrf<div class="mb-3"><label class="form-label">Subject</label><input name="subject" class="form-control" value="Re: {{ $enquiry->subject ?: 'Your enquiry' }}"></div><div class="mb-3"><label class="form-label">Message</label><textarea name="message" rows="7" class="form-control" required></textarea></div><button class="btn btn-primary" @disabled(!$enquiry->email)>Send from Business Email</button>@if(!$enquiry->email)<small class="text-danger ms-2">Customer email not available.</small>@endif</form></div>
<div class="card p-4"><h5 class="fw-bold">Communication History</h5>@forelse($enquiry->communicationLogs as $log)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>{{ ucfirst($log->reply_type) }} · {{ strtoupper($log->channel) }}</strong><span class="badge text-bg-{{ $log->delivery_status==='sent'?'success':($log->delivery_status==='failed'?'danger':'secondary') }}">{{ $log->delivery_status }}</span></div><small class="text-muted">{{ $log->created_at->format('d M Y, h:i A') }} · {{ $log->sender }} → {{ $log->recipient }}</small><div class="mt-2"><strong>{{ $log->subject }}</strong></div><div class="mt-1">{{ $log->message_body }}</div>@if($log->failed_reason)<div class="text-danger small mt-2">{{ $log->failed_reason }}</div>@endif</div>@empty<p class="text-muted mb-0">No communication yet.</p>@endforelse</div>
</div>
<div class="col-xl-4">
<div class="card p-4 mb-4"><h5 class="fw-bold">Manage Enquiry</h5><form method="POST" action="{{ route('admin.enquiries.update',$enquiry) }}">@csrf @method('PATCH')<div class="mb-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['new','auto_replied','manual_review','replied','follow_up_due','in_progress','converted','admitted','no_response','closed'] as $status)<option value="{{ $status }}" @selected($enquiry->status===$status)>{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Priority</label><select name="priority" class="form-select">@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}" @selected($enquiry->priority===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Category</label><input name="category" value="{{ $enquiry->category }}" class="form-control"></div><div class="mb-3"><label class="form-label">Course / Service</label><input name="course_service" value="{{ $enquiry->course_service }}" class="form-control"></div><button class="btn btn-success w-100">Update</button></form></div>
<div class="card p-4 mb-4"><h5 class="fw-bold">Schedule Follow-up</h5><form method="POST" action="{{ route('admin.enquiries.follow-up',$enquiry) }}">@csrf<div class="mb-3"><input type="datetime-local" name="scheduled_at" class="form-control" required></div><div class="mb-3"><textarea name="note" class="form-control" rows="3" placeholder="Follow-up note"></textarea></div><button class="btn btn-outline-primary w-100">Schedule</button></form>@if($enquiry->followUps->isNotEmpty())<hr><small class="text-muted">Recent Follow-ups</small>@foreach($enquiry->followUps->take(3) as $f)<div class="small mt-2"><strong>{{ $f->scheduled_at?->format('d M, h:i A') }}</strong> · {{ $f->status }}<br>{{ $f->note }}</div>@endforeach @endif</div>
<form method="POST" action="{{ route('admin.enquiries.destroy',$enquiry) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100" onclick="return confirm('Move this enquiry to trash?')">Move to Trash</button></form>
</div></div>
@endsection
