@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h2 class="fw-bold mb-1">{{ auth()->user()?->isMasterAdmin() ? 'MCI Master Dashboard' : 'MCI Business Dashboard' }}</h2><p class="text-muted mb-0">Central enquiry, admission and communication overview.</p></div><a href="{{ route('home') }}" target="_blank" class="btn btn-outline-primary">View Website</a></div>

<div class="row g-3 mb-4">@foreach([['Total Enquiries',$enquiryCount],["Today's Enquiries",$todayEnquiryCount],['7-Day Enquiries',$sevenDayEnquiryCount],['30-Day Enquiries',$thirtyDayEnquiryCount],['30-Day Admissions',$thirtyDayAdmissionCount],['Conversion %',$thirtyDayConversionRate.'%'],['Delivery Success',$communicationSuccessRate.'%']] as [$label,$count])<div class="col-6 col-md-4 col-xl"><div class="card p-3 h-100"><div class="text-muted small text-uppercase fw-semibold">{{ $label }}</div><div class="display-6 fw-bold mt-2">{{ $count }}</div></div></div>@endforeach</div>

@if($failedCommunicationCount || $failedSyncCount || $manualReviewCount || $followUpDueCount)
<div class="alert alert-warning mb-4"><div class="fw-bold mb-2">Operational alerts need attention</div><div class="d-flex flex-wrap gap-3 small"><span>Failed messages: <strong>{{ $failedCommunicationCount }}</strong></span><span>Failed sync: <strong>{{ $failedSyncCount }}</strong></span><span>Manual review: <strong>{{ $manualReviewCount }}</strong></span><span>Follow-up due: <strong>{{ $followUpDueCount }}</strong></span></div></div>
@endif

<div class="card p-4 mb-4"><div class="d-flex justify-content-between align-items-center"><div><h5 class="fw-bold mb-1">Needs Attention</h5><small class="text-muted">Manual review, failed sync and overdue follow-ups.</small></div><a href="{{ route('admin.enquiries.index') }}">View all enquiries</a></div><div class="table-responsive mt-3"><table class="table align-middle mb-0"><thead><tr><th>Customer</th><th>Business</th><th>Reason</th><th>Received</th><th></th></tr></thead><tbody>@forelse($needsAttention as $item)<tr><td>{{ $item->name }}<br><small>{{ $item->phone }}</small></td><td>{{ $item->institution?->name ?: '-' }}</td><td>@if($item->auto_reply_status==='manual_review')Manual Review @elseif($item->sync_status==='failed')Sync Failed @elseif($item->next_follow_up_at && $item->next_follow_up_at->isPast())Follow-up Overdue @else Attention Required @endif</td><td>{{ $item->created_at->format('d M Y H:i') }}</td><td><a href="{{ route('admin.enquiries.show',$item) }}">Open</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Nothing needs attention right now.</td></tr>@endforelse</tbody></table></div></div>

@if($businessPerformance->isNotEmpty())
<div class="card p-4 mb-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="fw-bold mb-1">30-Day Business Performance</h5><small class="text-muted">Comparative enquiry, admission and communication performance.</small></div><a href="{{ route('admin.reports.index') }}">Open detailed reports</a></div><div class="table-responsive mt-3"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>Business</th><th>Enquiries</th><th>Admissions</th><th>Messages Sent</th><th>Failures</th><th>Delivery %</th></tr></thead><tbody>@foreach($businessPerformance as $row)<tr><td>{{ $loop->iteration }}</td><td class="fw-semibold">{{ $row->institution->name }}</td><td>{{ $row->enquiries }}</td><td>{{ $row->admissions }}</td><td>{{ $row->sent }}</td><td>{{ $row->failed }}</td><td>{{ $row->delivery_rate }}%</td></tr>@endforeach</tbody></table></div></div>
@endif

<div class="row g-4">@foreach([['Central Enquiries',$enquiryCount,'admin.enquiries.index'],['Admissions',$admissionCount,'admin.admissions.index'],['Customers','—','admin.customers.index'],['Communication History','—','admin.communications.index'],['Follow-ups',$followUpDueCount,'admin.follow-ups.index'],['Reports','—','admin.reports.index']] as [$label,$count,$route])<div class="col-sm-6 col-xl-4"><div class="card p-4 h-100"><div class="text-muted small text-uppercase fw-semibold">{{ $label }}</div><div class="display-5 fw-bold my-2">{{ $count }}</div><a href="{{ route($route) }}" class="text-decoration-none">Manage {{ $label }} →</a></div></div>@endforeach
@if(auth()->user()?->isMasterAdmin())@foreach([['Institutions / Businesses',$institutionCount,'admin.institutions.index'],['News & Events',$newsCount,'admin.news.index'],['Gallery',$galleryCount,'admin.gallery.index'],['Downloads',$downloadCount,'admin.downloads.index']] as [$label,$count,$route])<div class="col-sm-6 col-xl-4"><div class="card p-4 h-100"><div class="text-muted small text-uppercase fw-semibold">{{ $label }}</div><div class="display-5 fw-bold my-2">{{ $count }}</div><a href="{{ route($route) }}" class="text-decoration-none">Manage {{ $label }} →</a></div></div>@endforeach @endif</div>
@endsection
